### ISSUE TITLE
data-test-* attributes without values on components cause build error

### ISSUE THREAD

**Issue by denzo** [simplabs/ember-test-selectors#71]
In the release notes for `v0.2.0` it states

> Added support for data-test-* attributes without values on components

I'm using:
```
ember-cli: 2.11.1
ember: 2.11.2
ember-test-selectors: 0.2.1
```
If I do the following
```hbs
{{my-component data-test-special-button}}
```
I get a Build Error with:
```
Expecting 'EQUALS'
```
The current workaround is:
```hbs
{{my-component data-test-special-button=true}}
```

**Comment by Turbo87** [comment]
@denzo I tried to reproduce your problem but wasn't successful. here are the steps that I've tried:

- `ember new selector-test`
- `cd selector-test`
- `ember install ember-test-selectors`
- `ember generate component my-component`
- add `{{my-component data-test-special-button}}` to `app/templates/application.hbs`
- `ember serve`

I expected `ember serve` to fail with a build error, but it ran fine.

**Comment by denzo** [comment]
The good old `rm -rf node_modules` and `npm i` resolved the issue 🙈

**Comment by marcoow** [comment]
argh… closing this then

**Comment by pangratz** [comment]
I am running into this using `{{number-spinner data-test-number-spinner}}`. A `nom` didn't help either 😞 

```hbs
{{#if showNumberSpinner}}
  {{number-spinner disabled=isDisabled value=currentValue min=min max=max update=(action "updateNumber") data-test-number-spinner}}
{{/if}}
```

```
The Broccoli Plugin: [broccoli-persistent-filter:TemplateCompiler] failed with:
Error: Parse error on line 17:
...-test-number-spinner}}{{/if}}<p class
-----------------------^
Expecting 'EQUALS', got 'CLOSE'
    at Object.parseError (/Users/clemens/development/projects/leproject/node_modules/ember-source/dist/ember-template-compiler.js:25768:23)
    at Object.parse (/Users/clemens/development/projects/leproject/node_modules/ember-source/dist/ember-template-compiler.js:25837:34)
    at Object.parse (/Users/clemens/development/projects/leproject/node_modules/ember-source/dist/ember-template-compiler.js:25420:59)
    at Object.preprocess (/Users/clemens/development/projects/leproject/node_modules/ember-source/dist/ember-template-compiler.js:23793:77)
    at precompile (/Users/clemens/development/projects/leproject/node_modules/ember-source/dist/ember-template-compiler.js:12081:34)
    at Object.precompile (/Users/clemens/development/projects/leproject/node_modules/ember-source/dist/ember-template-compiler.js:11221:12)
    at Object.template (/Users/clemens/development/projects/leproject/node_modules/ember-cli-htmlbars/utils.js:29:40)
    at TemplateCompiler.processString (/Users/clemens/development/projects/leproject/node_modules/ember-cli-htmlbars/index.js:68:36)
    at Promise.then.result.output (/Users/clemens/development/projects/leproject/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
    at initializePromise (/Users/clemens/development/projects/leproject/node_modules/rsvp/dist/rsvp.js:588:5)
    at new Promise (/Users/clemens/development/projects/leproject/node_modules/rsvp/dist/rsvp.js:1076:31)
    at /Users/clemens/development/projects/leproject/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:40:18
    at tryCatch (/Users/clemens/development/projects/leproject/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/clemens/development/projects/leproject/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/clemens/development/projects/leproject/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/clemens/development/projects/leproject/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by Turbo87** [comment]
We are handling `data-test-number-spinner` as a positional parameter here and are transforming it into `data-test-number-spinner=true` in an AST transform. The parser initially sees it as a position parameter though and positional parameter have to be written before named parameters.

If you change

```hbs
{{#if showNumberSpinner}}
  {{number-spinner disabled=isDisabled value=currentValue min=min max=max update=(action "updateNumber") data-test-number-spinner}}
{{/if}}
```

to

```hbs
{{#if showNumberSpinner}}
  {{number-spinner data-test-number-spinner disabled=isDisabled value=currentValue min=min max=max update=(action "updateNumber")}}
{{/if}}
```

it should work.

**Comment by pangratz** [comment]
> it should work.

... it does 🤦‍♂️

**Comment by Turbo87** [comment]
whaaaaaaat, there is a facepalm emoji on GitHub now?!? 😄

**Comment by jenweber** [comment]
@Turbo87 is it always the case that the test selectors need to come last when used on components? I ran into this issue myself today. I instinctively put them at the end of my component declaration. If that is the case, I can PR a README clarification.

**Comment by Turbo87** [comment]
> is it always the case that the test selectors need to come last when used on components?

no, the contrary is true. if you use a test selector key **without a value** it needs to come before any named args, otherwise it trips up the parser.
